/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'DSIVARAM' at '3/7/17 3:16 PM' with Gradle 2.8
 *
 * @author DSIVARAM, @date 3/7/17 3:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
